# Stage 1: Base image with dependencies
FROM ubuntu:latest as base
RUN apt-get update && \
        apt-get install -y python3 python3-pip postgresql-client libpq-dev libcurl4-openssl-dev libssl-dev && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

# Stage 2: Install pipenv and dependencies
FROM base as dependencies
RUN pip3 install pipenv
WORKDIR /app
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy

# Stage 3: Final image for running the application
FROM dependencies as final
COPY bin bin
COPY server server
COPY scripts scripts

# Add hot-reload to celery worker
# ENV LANG=C.UTF-8
CMD ["pipenv", "--python", "/usr/bin/python3", "run", "watchmedo", "auto-restart", "--directory", "server", "--recursive", "--pattern", "*.py", "--", "pipenv", "run", "celery", "--app", "server.tasks.studyoracle", "worker", "--loglevel=info"]

# CMD ["celery", "--app", "server.tasks.studyoracle", "worker", "--loglevel=info"]