# Stage 1: Base image with dependencies
FROM ubuntu:latest
RUN apt-get update && \
        apt-get install -y python3 python3-pip postgresql-client libpq-dev libcurl4-openssl-dev libssl-dev && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

# Stage 2: Install pipenv and dependencies
RUN pip3 install pipenv
WORKDIR /app
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy

# Stage 3: Final image for running the application
COPY bin bin
COPY server server
CMD ["flask", "--app", "server", "run", "--debug", "--host", "0.0.0.0", "--port", "8080"]