#!/bin/bash

# run npm run build in frontend
# cd frontend && npm run build && cd ..
# cp -r frontend/build/ server/frontend/build/

# push everything to AWS
terraform apply \
    -auto-approve \
    -replace=aws_ecr_repository.studyoracle_server \
    -replace=aws_ecr_repository.studyoracle_worker \
    -replace=aws_route53_record.studyoracle