#!/bin/bash

# run npm run build in frontend
cd frontend && npm run build && cd ..
cp -r frontend/build/ server/frontend/build/

# create new self-signed SSL certificates
# cd bin/certificates && ./generate.sh && cd ../..

# push everything to AWS
terraform apply \
    -auto-approve \
    -replace=aws_ecr_repository.studyoracle_server \
    -replace=aws_ecr_repository.studyoracle_worker \
    -replace=aws_ecs_cluster.studyoracle \
    -replace=aws_ecs_service.studyoracle \
    -replace=aws_ecs_task_definition.studyoracle_worker \
    -replace=aws_ecs_task_definition.studyoracle_server \
    -replace=aws_route53_record.studyoracle
